spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/surest
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000
      pool-name: HikariCP

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.time.timezone: UTC
      open-in-view: false

  redis:
    host: localhost
    port: 6379

server:
  port: 9090

jwt:
  secret: y7tX0Xc7jQhD7jX1eY3pA4KfQ5zJ8XwRrM2xH+9vY3M=
  expiration-ms: 3600000
